### ISSUE TITLE
neutron_subnet.managed() tries to add a already assigned router

### ISSUE THREAD

**Issue by 0xf10e** [fraunhoferfokus/openstack-formula#3]
Running [state.sls openstack.tests](https://github.com/fraunhoferfokus/openstack-formula/blob/master/openstack/tests.sls) I've just realized we don't check wether the subnet already has the given router assigned:

```
----------
          ID: test-subnet
    Function: neutron_subnet.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1563, in call
                  **cdata['kwargs'])
                File "/var/cache/salt/minion/extmods/states/neutron_subnet.py", line 191, in managed
                  router=router, subnet=subnet['name'])
                File "/var/cache/salt/minion/extmods/modules/neutron.py", line 406, in router_add_interface
                  raise neutron_exceptions.NeutronClientException
              NeutronClientException: An unknown exception occurred.
     Started: 22:10:23.479530
    Duration: 2582.09 ms
     Changes:   
```

From one of my test-controller's `/var/log/salt/minion`:

```
2015-06-12 22:10:28,928 [neutronclient.v2_0.client][DEBUG   ][7817] Error message: {"NeutronError": {"message": "Bad router request: Router already has a port on subnet 3fb813ce-7f28-40e7-a53f-137a00b52434", "type": "BadRequest", "detail": ""}}
2015-06-12 22:10:28,929 [salt.loaded.ext.module.neutron][ERROR   ][7817] Calling neutron.add_interface_router(8afd9ee7-dd37-47f3-b2e1-42805e984a61, {'subnet_id': u'3fb813ce-7f28-40e7-a53f-137a00b52434', 'admin_state_up': True})caused:
400-{u'NeutronError': {u'message': u'Bad router request: Router already has a port on subnet 3fb813ce-7f28-40e7-a53f-137a00b52434', u'type': u'BadRequest', u'detail': u''}}
2015-06-12 22:10:28,929 [salt.state       ][ERROR   ][7817] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1563, in call
    **cdata['kwargs'])
  File "/var/cache/salt/minion/extmods/states/neutron_subnet.py", line 191, in managed
    router=router, subnet=subnet['name'])
  File "/var/cache/salt/minion/extmods/modules/neutron.py", line 406, in router_add_interface
    raise neutron_exceptions.NeutronClientException
NeutronClientException: An unknown exception occurred.
```

Probably needs support for the [Ports binding extended attributes](http://developer.openstack.org/api-ref-networking-v2-ext.html#port_binding-ext) part of the Neutron-API.

**Comment by 0xf10e** [comment]
Fixed in https://github.com/fraunhoferfokus/openstack-formula/commit/55e3681c59af01384fdbc60c3b4ca36334df46f4 (though this code needs some clean-up, see #4).
